site_name: Personal Docs
theme:
  name: material
  logo: assets/logo.png
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
          icon: material/weather-night
          name: Switch to light mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/weather-night
          name: Switch to light mode
        primary: "lime"
        accent: "light green"
      # Palette toggle for dark mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
        primary: deep orange
        accent: red

  icon:
    logo: material/book

docs_dir: src
site_dir: docs

nav:
  - Home: index.md
  - Problemi Isola: 'isola.md'

markdown_extensions:
  - footnotes
  - smarty
  - toc:
      permalink: True
  - sane_lists
  - codehilite

  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      lang: it
  - tags
